name: hashit
version: 3.3.8
summary: hashit is an replacement for (md5sum, sha1sum, and so on)
icon: icon.png
description: |
  Hashit is an hashing program which can be uses to hash and verify muliple files on a system.
  I got the idea from an ubuntu iso image which have this hash table, so i got the idea to make
  such a program using python.
  I also found that the linux 'standard' hashing commands was named like this
  
        md5sum
        sha1sum
        sha256sum
        cksum
        sum
  
  hashname + sum, which i thougth was a pretty lame naming convention.

grade: stable
confinement: strict

apps:
  hashit:
    command: bin/hashit
    plugs: [home, removable-media]

parts:
  hashit:
    plugin: python
    python-version: python3
    source: .
