source 'https://rubygems.org'

# Updated versions.
gem "jekyll", ">= 3.7.4"
gem "ffi", ">= 1.9.24"https://github.com/cjavad/hashit/compare/a0173adebe558e7e0aa992e64339daa776943ce4...4d81ee79fd0e22368db350534935a91e3ec23c0d


gem "jekyll-theme-dinky"
# Plugins
gem 'jekyll-relative-links'
